name: 'Nullplatform Login'
description: 'Github Action to automate the login process on Nullplatform'
inputs:
  token:
    description: 'encoded access token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
