name: "Nullplatform Login"
description: "Github Action to automate the login process on Nullplatform"
inputs:
  access-key:
    description: "access key"
    required: false
    deprecationMessage: "this is not implemented yet"
  secret-access-key:
    description: "secret access key"
    required: false
    deprecationMessage: "this is not implemented yet"
  token:
    description: "encoded nullplatform token"
    required: false
    deprecationMessage: "*token* input is deprecated, use *api-key* instead"
  api-key:
    description: "nullplatform api key"
    required: false
outputs:
  access-token:
    description: "The nullplatform access token"
runs:
  using: "node20"
  main: "dist/index.js"
