name: "Nullplatform Login"
description: "Github Action to automate the login process on Nullplatform"
inputs:
  access-key:
    description: "access key"
    required: false
  secret-access-key:
    description: "secret access key"
    required: false
  token:
    description: "encoded nullplatform token"
    required: false
outputs:
  access-token:
    description: "The nullplatform access token"
runs:
  using: "node16"
  main: "dist/index.js"
